# import pandas as pd

In [3]:
df_2010=pd.read_excel("D:\online+retail+ii-1\Online Retail Data.xlsx", sheet_name="Year 2010-2011")

In [4]:
df_2010['InvoiceDate'] = pd.to_datetime(df_2010['InvoiceDate'])

In [5]:
df_2010_2011 = df_2010[df_2010['InvoiceDate'].dt.year == 2010]

In [6]:
# Random sample of 10,000 rows
df = df_2010_2011.sample(n=10000, random_state=42)

In [9]:
#Exploring the dataset
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
39870,539708,35924,HANGING FAIRY CAKE DECORATION,1,2010-12-21 12:18:00,4.21,NaN,United Kingdom
33310,539246,85114C,RED ENCHANTED FOREST PLACEMAT,8,2010-12-16 13:33:00,1.65,14606.0,United Kingdom
624,536415,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,5,2010-12-01 11:57:00,2.95,12838.0,United Kingdom
11578,537254,20975,12 PENCILS SMALL TUBE RED RETROSPOT,4,2010-12-06 11:01:00,0.65,15898.0,United Kingdom
30427,538864,21485,RETROSPOT HEART HOT WATER BOTTLE,24,2010-12-14 14:26:00,4.25,17739.0,United Kingdom

In [10]:
df.tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
41210,539760,15036,ASSORTED COLOURS SILK FAN,12,2010-12-21 17:16:00,0.75,17400.0,United Kingdom
19055,537827,22145,CHRISTMAS CRAFT HEART STOCKING,30,2010-12-08 14:43:00,2.10,15332.0,Lithuania
5513,536864,21488,RED WHITE SCARF HOT WATER BOTTLE,1,2010-12-03 11:27:00,8.47,NaN,United Kingdom
22171,538153,82599,FANNY'S REST STOPMETAL SIGN,1,2010-12-09 16:31:00,4.21,NaN,United Kingdom
42301,539981,85099B,JUMBO BAG RED RETROSPOT,10,2010-12-23 14:35:00,1.95,13304.0,United Kingdom

In [11]:
df.describe()

           Quantity                    InvoiceDate         Price   Customer ID
count  10000.000000                          10000  10000.000000   6334.000000
mean       7.193600  2010-12-10 16:25:01.973999872      6.605233  15490.827281
min    -9360.000000            2010-12-01 08:26:00      0.000000  12347.000000
25%        1.000000            2010-12-06 09:58:00      1.280000  14135.000000
50%        2.000000            2010-12-09 14:09:00      2.510000  15544.000000
75%        7.000000            2010-12-15 14:25:00      4.650000  17069.000000
max     1824.000000            2010-12-23 16:49:00  13541.330000  18269.000000
std       99.712289                            NaN    148.030499   1739.345921

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 39870 to 42301
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice      10000 non-null  object
 1   StockCode    10000 non-null  object
 2   Description  9975 non-null   object
 3   Quantity     10000 non-null  int64
 4   InvoiceDate  10000 non-null  datetime64[ns]
 5   Price        10000 non-null  float64
 6   Customer ID  6334 non-null   float64
 7   Country      10000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 703.1+ KB

In [13]:
df.shape

(10000, 8)

In [14]:
df[df['Customer ID'].isnull()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
39870,539708,35924,HANGING FAIRY CAKE DECORATION,1,2010-12-21 12:18:00,4.21,NaN,United Kingdom
11359,537240,85177,BASKET OF FLOWERS SEWING KIT,2,2010-12-06 10:08:00,1.66,NaN,United Kingdom
21278,538071,85096,HILDA CANDY SPOT RABBIT,1,2010-12-09 14:09:00,7.62,NaN,United Kingdom
40813,539743,22135,MINI LADLE LOVE HEART PINK,1,2010-12-21 15:20:00,0.85,NaN,United Kingdom
10709,537237,82582,AREA PATROLLED METAL SIGN,1,2010-12-06 09:58:00,4.21,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
5859,536876,22419,LIPSTICK PEN RED,7,2010-12-03 11:36:00,0.85,NaN,United Kingdom
10331,537237,21641,ASSORTED TUTTI FRUTTI KEYRING BALL,1,2010-12-06 09:58:00,1.66,NaN,United Kingdom
22610,538177,20682,RED RETROSPOT CHILDRENS UMBRELLA,2,2010-12-10 09:51:00,6.77,NaN,United Kingdom
5513,536864,21488,RED WHITE SCARF HOT WATER BOTTLE,1,2010-12-03 11:27:00,8.47,NaN,United Kingdom
22171,538153,82599,FANNY'S REST STOPMETAL SIGN,1,2010-12-09 16:31:00,4.21,NaN,United Kingdom

In [15]:
df[df['Description'].isnull()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
14217,537466,21488,NaN,-50,2010-12-07 10:33:00,0.0,NaN,United Kingdom
19625,537872,21595,NaN,1,2010-12-08 18:07:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
1985,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
14064,537453,21248,NaN,-18,2010-12-07 09:28:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
22581,538173,22353,NaN,-28,2010-12-10 09:35:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
20330,538038,21488,NaN,8,2010-12-09 13:07:00,0.0,NaN,United Kingdom
14065,537454,21349,NaN,-44,2010-12-07 09:30:00,0.0,NaN,United Kingdom
19628,537877,21661,NaN,1,2010-12-08 18:08:00,0.0,NaN,United Kingdom
12068,537361,21777,NaN,5,2010-12-06 12:34:00,0.0,NaN,United Kingdom
20394,538043,22833,NaN,-1,2010-12-09 13:10:00,0.0,NaN,United Kingdom
34608,539413,22959,NaN,12,2010-12-17 13:44:00,0.0,NaN,United Kingdom
1510,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
7212,537020,21807,NaN,-30,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7201,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
21789,538139,84802A,NaN,2,2010-12-09 15:57:00,0.0,NaN,United Kingdom
20494,538054,85167B,NaN,-24,2010-12-09 13:34:00,0.0,NaN,United Kingdom
22295,538160,20956,NaN,288,2010-12-09 17:18:00,0.0,NaN,United Kingdom
19599,537870,21486,NaN,-77,2010-12-08 17:08:00,0.0,NaN,United Kingdom
21791,538143,84534B,NaN,1,2010-12-09 15:58:00,0.0,NaN,United Kingdom
2022,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
22294,538159,21324,NaN,-18,2010-12-09 17:17:00,0.0,NaN,United Kingdom

In [16]:
df[df['Invoice']==0].shape[0]

0

In [17]:
df[df['StockCode']==0].shape[0]

0

In [18]:
df[df['Description'].isna()].shape[0]

25

In [19]:
df[df['Quantity']<0].shape[0]

167

In [20]:
df[df['Quantity']==0].shape[0]

0

In [21]:
df[df['InvoiceDate'].isnull()].shape[0]

0

In [22]:
df[df['Price']==0].shape[0]

53

In [23]:
df[df['Price']<0].shape[0]

0

In [24]:
df[df['Customer ID'].isna()].shape[0]

3666

In [25]:
df[df['Country'].isnull()].shape[0]

0

In [26]:
df['Country'].unique()

array(['United Kingdom', 'Germany', 'Switzerland', 'EIRE', 'Finland',
       'France', 'Spain', 'Belgium', 'Japan', 'Poland', 'Cyprus',
       'Norway', 'Iceland', 'Portugal', 'Australia', 'Lithuania',
       'Netherlands', 'Italy', 'Austria', 'Sweden', 'Denmark',
       'Channel Islands'], dtype=object)

In [27]:
#Droping Duplicates
df.duplicated().sum()

np.int64(25)

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.shape

(9975, 8)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9975 entries, 39870 to 42301
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice      9975 non-null   object
 1   StockCode    9975 non-null   object
 2   Description  9950 non-null   object
 3   Quantity     9975 non-null   int64
 4   InvoiceDate  9975 non-null   datetime64[ns]
 5   Price        9975 non-null   float64
 6   Customer ID  6309 non-null   float64
 7   Country      9975 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 701.4+ KB

In [31]:
#Standardizing Data
#Invoice Cleaning
df['Invoice'].unique()

array([539708, 539246, 536415, ..., 539865, 538871, 537827],
      shape=(1437,), dtype=object)

In [32]:
invoice_letter = df['Invoice'].astype(str).str.contains('[a-zA-Z]',regex=True)

In [33]:
print(df[invoice_letter]['Invoice'].unique())

['C537602' 'C539644' 'C538834' 'C538341' 'C537251' 'C537860' 'C538882'
 'C538833' 'C537157' 'C538874' 'C538084' 'C537853' 'C537647' 'C538898'
 'C536812' 'C537684' 'C537857' 'C538103' 'C536817' 'C539069' 'C539573'
 'C539950' 'C538059' 'C537788' 'C537402' 'C537164' 'C539067' 'C537132'
 'C538376' 'C538681' 'C536548' 'C539632' 'C539657' 'C539602' 'C536822'
 'C538115' 'C538682' 'C538350' 'C539276' 'C538377' 'C538314' 'C539603'
 'C538643' 'C538705' 'C536543' 'C539605' 'C538119' 'C538102' 'C539104'
 'C537856' 'C539066' 'C537807' 'C539273' 'C537797' 'C536854' 'C539270'
 'C539945' 'C539943' 'C539058' 'C538052' 'C539709' 'C537805' 'C539947'
 'C539097' 'C539031' 'C538100' 'C539661' 'C539576' 'C539606' 'C538105'
 'C539221' 'C537893' 'C538650' 'C539114' 'C539486' 'C539956' 'C536850'
 'C536391' 'C536642' 'C537600' 'C538726' 'C539832' 'C538362' 'C536814'
 'C536828' 'C538536' 'C537812' 'C539071' 'C538713' 'C538693' 'C537835'
 'C537832' 'C539054' 'C538123' 'C538595' 'C539711' 'C539667' 'C538109'
 'C538531' 'C538628' 'C539274' 'C537039' 'C538124' 'C539596' 'C539608'
 'C536757' 'C537383' 'C539574' 'C539589' 'C539598' 'C538768' 'C537746'
 'C538723']

In [34]:
print(df[invoice_letter]['Invoice'].shape[0])

153

In [35]:
cancel_orders=df[invoice_letter & (df['Quantity']>0)]
print(cancel_orders)

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [36]:
import numpy as np

In [37]:
df['Order_Status']=np.where(invoice_letter,'Cancelled','Completed')

In [38]:
df[invoice_letter]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status
14528,C537602,22654,DELUXE SEWING KIT,-1,2010-12-07 12:45:00,4.95,17511.0,United Kingdom,Cancelled
39450,C539644,21578,WOODLAND DESIGN COTTON TOTE BAG,-2,2010-12-20 15:52:00,2.25,12471.0,Germany,Cancelled
29948,C538834,22618,COOKING SET RETROSPOT,-1,2010-12-14 13:06:00,9.95,14415.0,United Kingdom,Cancelled
24176,C538341,22727,ALARM CLOCK BAKELIKE RED,-2,2010-12-10 14:03:00,3.75,15514.0,United Kingdom,Cancelled
11511,C537251,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9,2010-12-06 10:45:00,2.55,NaN,United Kingdom,Cancelled
...,...,...,...,...,...,...,...,...,...
24915,C538350,85099F,JUMBO BAG STRAWBERRY,-2,2010-12-10 15:01:00,1.65,13798.0,United Kingdom,Cancelled
38949,C539605,21314,SMALL GLASS HEART TRINKET POT,-3,2010-12-20 14:07:00,2.10,13050.0,United Kingdom,Cancelled
17354,C537746,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,-1,2010-12-08 11:03:00,3.25,15021.0,United Kingdom,Cancelled
4877,C536814,72799E,IVORY PILLAR CANDLE SILVER FLOCK,-6,2010-12-02 17:03:00,2.95,13958.0,United Kingdom,Cancelled
29279,C538723,21217,RED RETROSPOT ROUND CAKE TINS,-1,2010-12-14 11:12:00,9.95,12434.0,Australia,Cancelled

In [39]:
df['Invoice']=df['Invoice'].astype(str).str.extract(r'(\d+)')

In [40]:
verify_invoice = df['Invoice'].astype(str).str.contains('[a-zA-Z]',regex=True)

In [41]:
print(df[verify_invoice]['Invoice'].unique())

[]

In [42]:
#StockCode Cleaning
stock_letter = df['StockCode'].astype(str).str.contains('[a-zA-Z]',regex=True)

In [43]:
print(df[stock_letter]['StockCode'].unique())

['85114C' '85135C' '90130B' '85132A' '35004B' '84559a' '85035A' '84030E'
 '47343A' '85049A' '84913A' '85049G' '84596G' '17012C' '82494L' 'M'
 '85049E' '84997A' '84520B' '90211B' '85123A' '84313C' '82613D' '17012D'
 '84968F' '48173c' '84884a' '84997C' '84029E' '15056N' '85014A' '72800E'
 '90200C' '47559B' '72351A' '85131D' '84870C' '47591D' '90024C' '85032D'
 '85099B' '35471D' '72807C' '18098C' '85231G' '84029G' '84031B' '47593B'
 '90013C' '84536B' '35095A' '85132B' '72800B' '85099C' '85040A' '35916C'
 'POST' '85231B' '85049H' '84970l' '84970S' '85131B' 'C2' '90183A'
 '72349B' '84406B' '85099F' '84849D' '84558A' 'AMAZONFEE' '47367B'
 '85017A' '46000P' '85184C' '84251B' '85169A' '72801d' '85035B' '85031A'
 '46000S' '84247G' '84031A' '85014B' '85169D' '84970L' '90081A' '18097C'
 '85035b' '35833G' '90198A' '82001S' '84032B' '17013D' '79051A' '84997D'
 '72760B' '85131C' '85123a' '85019C' '17091J' 'D' '15056P' '90214P'
 '84926D' '84459A' '84659A' '90214J' '90175A' '79191C' '84912B' '35598B'
 '47590A' '85114A' '79302M' '84536A' '17164B' '47567B' '85036C' '47599A'
 'DOT' '84535B' '85170D' '37444B' '84341B' '62096A' '17107D' '90129F'
 '47591d' '85049B' '84846A' '90013B' '84625A' '15056bl' '84509G' '62094B'
 '90060D' '90161D' '79030D' '84569B' '84913B' '84559B' '16156S' '90161C'
 '90177D' '85135B' '90082B' '15060B' '85136C' '85132C' '16168M' '90185A'
 '85132a' '82613B' '82494l' '90214S' '90162D' '90018B' '85163A' '90200A'
 '37482P' '90178B' '35598D' '90214C' '84032A' '72807A' '84510C' '85180A'
 '35833P' '72802C' '90200D' '84247E' '15056BL' '85199S' '37479P' '82616B'
 '72807B' '85039C' '47594A' '15056n' '85025C' '85186A' '72802A' '85039A'
 '84795B' '48173C' '85232D' '35004C' '85039B' '84877D' '90199C' '90198B'
 '35599B' '90177E' '90161A' '90018A' '84279P' '47599B' '85036B' '37444A'
 '90160B' '85169B' '84509B' '84625C' '85034B' '90202C' '90214Z' '85034C'
 '84952C' '84569D' '47586A' '84971S' '84660C' '72802B' '79191B' '90129A'
 'gift_0001_50' '85071D' '90040B' '79144B' '85232B' '35810A' '90003C'
 '90214H' '79190B' '84507C' '90214E' '90126A' '84509C' '84997B' '84970s'
 '84558a' '90209B' '17084N' '90013D' '90019A' '84849B' '90206C' '47570B'
 '85017B' '85035C' '84519A' '84415B' 'gift_0001_40' '85136A' '47591B'
 '84898F' '84968D' '90214L' '15044C' '84997b' '85170B' '90195A' '79144C'
 '47369B' '85049D' '85232A' '17012E' '90214K' '84313B' '51014A' '90199D'
 '85061W' '46776B' '90129C' '72799E' '90000B' '18098c' '72351B' '47348A'
 '84806A' '85036A' '84596L' '47563A' '84802A' '79190A' '84660c' '84507B'
 '47504K' '82616C' '84519B' '85049C' '90214B' '85124C' '85179C' '84596F'
 '72799F' '84596E' '85194L' '85230G' '90120C' '16258A' '84912A' '84876D'
 '85114c' '35597B' '35001W' '90082A' '79190D' '90209C' '90160C' '90200B'
 '84509A' '90129E' '84993A' '84798A' '84709B' '90002D' '90210B' '72801G'
 '46115B' '79066K' '90059D' '84563B' '84534B' '84030e' '72803A' '85199L'
 '84968e' '17165D' '84559b' '84595E' '17090D' '84597B' '84086C' '85129C'
 '82613C' '85230F' '17012A' '47590B' '84706D' '47021G' '85032B' '17084R'
 '72800D' '84510A' '85170C' '85130B' '84596J' '84509c' '84856L' '90214I'
 '85230E' '46776C' '90210D' '35916A' '90129B' '90214D' '84531A' '16206B'
 '90214G' '90205A' '85129D' '90059A' '17012B' '46000M' '90201D' '90185D'
 '84508B' '85019A' '15044B' '84596b' '90181B' '18094C' '85027L' '79191D'
 '85180B' '85071A' '47559b' '90035A' '90179C' '77101A' '85049a' '82011C'
 '84459B' '90039C' '16161U' '84751B' '85160a' '35095B' '85099f' '84968A'
 '85131A' '85167B' '85170A' '84707A' '47503J' '84660A' '46775D' '90161B'
 '84870B' '47566B' '15056p' '72349b' '84951A' '84660B' '85034A' '17129F'
 '90162C' '90210A' '90200E' '35610A' '51014C' '90199B' '79149B' '16169N'
 '84925D' '51014L' '84707B' '84927E' '84711B' '90212B' '84429A' '85230B'
 '75013B' '84673B' '90186A' '90019C' '84795b' '90003E' '90152B' '35001G'
 '90178A' '85049F' '84952A' '35599D' '90214Y' '85183B' '85114B' '85185B'
 '47504H' '90214N']

In [44]:
stock_format=df['StockCode'].astype(str).str.contains(r'^\d+[a-zA-Z]*$',regex=True)

In [45]:
unique_stock=df[~stock_format]['StockCode'].unique()

In [46]:
print(unique_stock)

['M' 'POST' 'C2' 'AMAZONFEE' 'D' 'DOT' 'gift_0001_50' 'gift_0001_40']

In [54]:
type_mapping={'M':'Manual Adjustment',
              'POST':'Postage Fee',
              'C2':'Special Carriage Fee',
              'AMAZONFEE':'Platform Fee',
              'D':'Dicsount',
              'DOT':'Dotcom Overhead',
              'gift_0001_50':'Gift Voucher',
              'gift_0001_40':'Gift Voucher'
             }

In [55]:
df['StockCode']=df['StockCode'].replace(type_mapping)

In [56]:
print(df['StockCode'].value_counts())

StockCode
85123A    52
22834     48
22111     39
22837     38
22086     37
          ..
84596E     1
21379      1
85194L     1
72132      1
22145      1
Name: count, Length: 2056, dtype: int64

In [57]:
df['StockCode'].unique()

array([35924, '85114C', 22910, ..., '47504H', '90214N', 22145],
      shape=(2056,), dtype=object)

In [58]:
clean_stock=df['StockCode'].astype(str).str.contains(r'^\d+[a-zA-Z]*$',regex=True)

In [59]:
clean_two_stock=df[~clean_stock]['StockCode'].unique()

In [61]:
print(clean_two_stock)

['Manual Adjustmnt' 'Postage Fee' 'Special Carriage Fee' 'Platform Fee'
 'Dicsount' 'Dotcom Overhead' 'Gift Voucher']

In [70]:
lowercase_mask=df[df['StockCode'].astype(str).str.contains(r'[a-z]')].copy()
print(lowercase_mask)

      Invoice         StockCode                       Description  Quantity  \
40581  539738            84559a          3D SHEET OF DOG STICKERS         1
18186  537804  Manual Adjustmnt                            Manual        12
30703  538877            48173c              DOORMAT BLACK FLOCK          1
5676   536865            84884a       ANT WHITE WIRE HEART SPIRAL         1
40884  539744            84559a          3D SHEET OF DOG STICKERS         1
...       ...               ...                               ...       ...
38609  539589          Dicsount                          Discount        -1
5685   536865  Manual Adjustmnt                            Manual         1
34471  539391       Postage Fee                           POSTAGE         2
41045  539750            85099f              JUMBO BAG STRAWBERRY         2
15978  537642            84970l  SINGLE HEART ZINC T-LIGHT HOLDER         1

              InvoiceDate  Price  Customer ID         Country Order_Status
40581 2010-12-21 15:19:00   1.69          NaN  United Kingdom    Completed
18186 2010-12-08 13:17:00   0.19      12748.0  United Kingdom    Completed
30703 2010-12-14 15:29:00  16.98          NaN  United Kingdom    Completed
5676  2010-12-03 11:28:00   8.47          NaN  United Kingdom    Completed
40884 2010-12-21 15:21:00   1.69          NaN  United Kingdom    Completed
...                   ...    ...          ...             ...          ...
38609 2010-12-20 13:14:00  13.88      14527.0  United Kingdom    Cancelled
5685  2010-12-03 11:28:00   2.55          NaN  United Kingdom    Completed
34471 2010-12-17 11:51:00  15.00      12417.0         Belgium    Completed
41045 2010-12-21 15:40:00   5.06          NaN  United Kingdom    Completed
15978 2010-12-07 15:33:00   2.13          NaN  United Kingdom    Completed

[102 rows x 9 columns]

In [71]:
lowercase_mask['StockCode']=lowercase_mask['StockCode'].astype(str).str.upper()

In [72]:
df.update(lowercase_mask)

In [73]:
verify_lowercase=df[df['StockCode'].astype(str).str.contains(r'[a-z]')]
print(verify_lowercase)

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Order_Status]
Index: []

In [74]:
df['StockCode']=df['StockCode'].replace('MANUAL ADJUSTMNT','Manual Adjustment')

In [77]:
df['StockCode']=df['StockCode'].replace('POSTAGE FEE','Postage Fee')
df['StockCode']=df['StockCode'].replace('SPECIAL CARRIAGE FEE','Special Carriage Fee')
df['StockCode']=df['StockCode'].replace('PLATFORM FEE','Platform Fee')
df['StockCode']=df['StockCode'].replace('DICSOUNT','Discount')
df['StockCode']=df['StockCode'].replace('DOTCOM OVERHEAD','Dotcom Overhead')
df['StockCode']=df['StockCode'].replace('GIFT VOUCHER','Gift Voucher')

In [85]:
df[df['StockCode']=='Gift Voucher']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status
42057,539958,Gift Voucher,Dotcomgiftshop Gift Voucher £50.00,1,2010-12-23 13:26:00,42.55,NaN,United Kingdom,Completed
38248,539492,Gift Voucher,Dotcomgiftshop Gift Voucher £40.00,1,2010-12-20 10:14:00,34.04,NaN,United Kingdom,Completed

In [94]:
#Description Cleaning
special_char=df['Description'].astype(str).str.contains(r'[a-zA-Z\s]',na=False)

In [95]:
special_description=df[special_char]['Description'].unique()

In [96]:
print(special_description)

['HANGING FAIRY CAKE DECORATION' 'RED ENCHANTED FOREST PLACEMAT'
 'PAPER CHAIN KIT VINTAGE CHRISTMAS' ... 'ENGLISH ROSE SPIRIT LEVEL '
 'LETTER "N" BLING KEY RING' 'CHRISTMAS CRAFT HEART STOCKING ']

In [97]:
junk=df['Description'].astype(str).str.contains(r'^[?_\-:]+$',na=False)

In [98]:
print(df[junk]['Description'].unique())

[]

In [99]:
junk_index=df[df['Description']=='?'].index

In [100]:
df=df.drop(index=junk_index)

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9974 entries, 39870 to 42301
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Invoice       9974 non-null   object
 1   StockCode     9974 non-null   object
 2   Description   9949 non-null   object
 3   Quantity      9974 non-null   int64
 4   InvoiceDate   9974 non-null   datetime64[ns]
 5   Price         9974 non-null   float64
 6   Customer ID   6309 non-null   float64
 7   Country       9974 non-null   object
 8   Order_Status  9974 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 779.2+ KB

In [115]:
df[df['Description'].astype(str).str.isupper()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status
39870,539708,35924,HANGING FAIRY CAKE DECORATION,1,2010-12-21 12:18:00,4.21,NaN,United Kingdom,Completed
33310,539246,85114C,RED ENCHANTED FOREST PLACEMAT,8,2010-12-16 13:33:00,1.65,14606.0,United Kingdom,Completed
624,536415,22910,PAPER CHAIN KIT VINTAGE CHRISTMAS,5,2010-12-01 11:57:00,2.95,12838.0,United Kingdom,Completed
11578,537254,20975,12 PENCILS SMALL TUBE RED RETROSPOT,4,2010-12-06 11:01:00,0.65,15898.0,United Kingdom,Completed
30427,538864,21485,RETROSPOT HEART HOT WATER BOTTLE,24,2010-12-14 14:26:00,4.25,17739.0,United Kingdom,Completed
...,...,...,...,...,...,...,...,...,...
41210,539760,15036,ASSORTED COLOURS SILK FAN,12,2010-12-21 17:16:00,0.75,17400.0,United Kingdom,Completed
19055,537827,22145,CHRISTMAS CRAFT HEART STOCKING,30,2010-12-08 14:43:00,2.10,15332.0,Lithuania,Completed
5513,536864,21488,RED WHITE SCARF HOT WATER BOTTLE,1,2010-12-03 11:27:00,8.47,NaN,United Kingdom,Completed
22171,538153,82599,FANNY'S REST STOPMETAL SIGN,1,2010-12-09 16:31:00,4.21,NaN,United Kingdom,Completed
42301,539981,85099B,JUMBO BAG RED RETROSPOT,10,2010-12-23 14:35:00,1.95,13304.0,United Kingdom,Completed

In [122]:
df[df['Description'].astype(str).str.istitle()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,NaN,United Kingdom,Completed
33310,539246,85114C,Red Enchanted Forest Placemat,8,2010-12-16 13:33:00,1.65,14606.0,United Kingdom,Completed
624,536415,22910,Paper Chain Kit Vintage Christmas,5,2010-12-01 11:57:00,2.95,12838.0,United Kingdom,Completed
11578,537254,20975,12 Pencils Small Tube Red Retrospot,4,2010-12-06 11:01:00,0.65,15898.0,United Kingdom,Completed
30427,538864,21485,Retrospot Heart Hot Water Bottle,24,2010-12-14 14:26:00,4.25,17739.0,United Kingdom,Completed
...,...,...,...,...,...,...,...,...,...
41210,539760,15036,Assorted Colours Silk Fan,12,2010-12-21 17:16:00,0.75,17400.0,United Kingdom,Completed
19055,537827,22145,Christmas Craft Heart Stocking,30,2010-12-08 14:43:00,2.10,15332.0,Lithuania,Completed
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,NaN,United Kingdom,Completed
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,NaN,United Kingdom,Completed
42301,539981,85099B,Jumbo Bag Red Retrospot,10,2010-12-23 14:35:00,1.95,13304.0,United Kingdom,Completed

In [117]:
df['Description']=df['Description'].replace('Dotcomgiftshop Gift Voucher £50.00','Gift Voucher £50.00')
df['Description']=df['Description'].replace('Dotcomgiftshop Gift Voucher £40.00','Gift Voucher £40.00')

In [119]:
upper=df['Description'].apply(lambda x:isinstance(x,str) and x.isupper())
preview_df=df[upper][['Description']].copy()
preview_df['Proposed_description']=preview_df['Description'].str.title()
preview_df

,Description,Proposed_description
39870,HANGING FAIRY CAKE DECORATION,Hanging Fairy Cake Decoration
33310,RED ENCHANTED FOREST PLACEMAT,Red Enchanted Forest Placemat
624,PAPER CHAIN KIT VINTAGE CHRISTMAS,Paper Chain Kit Vintage Christmas
11578,12 PENCILS SMALL TUBE RED RETROSPOT,12 Pencils Small Tube Red Retrospot
30427,RETROSPOT HEART HOT WATER BOTTLE,Retrospot Heart Hot Water Bottle
...,...,...
41210,ASSORTED COLOURS SILK FAN,Assorted Colours Silk Fan
19055,CHRISTMAS CRAFT HEART STOCKING,Christmas Craft Heart Stocking
5513,RED WHITE SCARF HOT WATER BOTTLE,Red White Scarf Hot Water Bottle
22171,FANNY'S REST STOPMETAL SIGN,Fanny'S Rest Stopmetal Sign
42301,JUMBO BAG RED RETROSPOT,Jumbo Bag Red Retrospot

In [120]:
is_upper=df['Description'].apply(lambda x:isinstance(x,str) and x.isupper())
df.loc[is_upper,'Description']=df.loc[is_upper,'Description'].str.title()

In [123]:
df[df['Description']=='Manual']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status
18186,537804,Manual Adjustment,Manual,12,2010-12-08 13:17:00,0.19,12748.0,United Kingdom,Completed
7976,537077,Manual Adjustment,Manual,12,2010-12-05 11:59:00,0.42,17062.0,United Kingdom,Completed
28993,538681,Manual Adjustment,Manual,-1,2010-12-13 17:12:00,316.30,NaN,United Kingdom,Cancelled
28994,538682,Manual Adjustment,Manual,-1,2010-12-13 17:14:00,1130.90,NaN,United Kingdom,Cancelled
2239,536569,Manual Adjustment,Manual,1,2010-12-01 15:35:00,1.25,16274.0,United Kingdom,Completed
13954,537435,Manual Adjustment,Manual,2,2010-12-06 16:58:00,5.95,17920.0,United Kingdom,Completed
12783,537396,Manual Adjustment,Manual,1,2010-12-06 14:08:00,35.00,17223.0,United Kingdom,Completed
21758,538124,Manual Adjustment,Manual,-4,2010-12-09 15:43:00,0.50,15329.0,United Kingdom,Cancelled
28007,538597,Manual Adjustment,Manual,1,2010-12-13 12:26:00,1.25,15555.0,United Kingdom,Completed
5685,536865,Manual Adjustment,Manual,1,2010-12-03 11:28:00,2.55,NaN,United Kingdom,Completed

In [124]:
#Invoice Date Extract Columns
print(df['InvoiceDate'].dtype)

datetime64[ns]

In [160]:
df['Invoice_Date_Only']=df['InvoiceDate'].dt.date

In [161]:
df['Week_Beginning']=df['InvoiceDate'].dt.to_period('W').dt.start_time

In [162]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,0,United Kingdom,Completed,2010-12-21,2010-12-20
33310,539246,85114C,Red Enchanted Forest Placemat,8,2010-12-16 13:33:00,1.65,14606,United Kingdom,Completed,2010-12-16,2010-12-13
624,536415,22910,Paper Chain Kit Vintage Christmas,5,2010-12-01 11:57:00,2.95,12838,United Kingdom,Completed,2010-12-01,2010-11-29
11578,537254,20975,12 Pencils Small Tube Red Retrospot,4,2010-12-06 11:01:00,0.65,15898,United Kingdom,Completed,2010-12-06,2010-12-06
30427,538864,21485,Retrospot Heart Hot Water Bottle,24,2010-12-14 14:26:00,4.25,17739,United Kingdom,Completed,2010-12-14,2010-12-13
...,...,...,...,...,...,...,...,...,...,...,...
41210,539760,15036,Assorted Colours Silk Fan,12,2010-12-21 17:16:00,0.75,17400,United Kingdom,Completed,2010-12-21,2010-12-20
19055,537827,22145,Christmas Craft Heart Stocking,30,2010-12-08 14:43:00,2.10,15332,Lithuania,Completed,2010-12-08,2010-12-06
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,0,United Kingdom,Completed,2010-12-03,2010-11-29
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,0,United Kingdom,Completed,2010-12-09,2010-12-06
42301,539981,85099B,Jumbo Bag Red Retrospot,10,2010-12-23 14:35:00,1.95,13304,United Kingdom,Completed,2010-12-23,2010-12-20

In [163]:
#Customer ID clean
print(df['Customer ID'].dtype)

Int64

In [164]:
df['Customer ID']=df['Customer ID'].astype('Int64')

In [165]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,0,United Kingdom,Completed,2010-12-21,2010-12-20
33310,539246,85114C,Red Enchanted Forest Placemat,8,2010-12-16 13:33:00,1.65,14606,United Kingdom,Completed,2010-12-16,2010-12-13
624,536415,22910,Paper Chain Kit Vintage Christmas,5,2010-12-01 11:57:00,2.95,12838,United Kingdom,Completed,2010-12-01,2010-11-29
11578,537254,20975,12 Pencils Small Tube Red Retrospot,4,2010-12-06 11:01:00,0.65,15898,United Kingdom,Completed,2010-12-06,2010-12-06
30427,538864,21485,Retrospot Heart Hot Water Bottle,24,2010-12-14 14:26:00,4.25,17739,United Kingdom,Completed,2010-12-14,2010-12-13
...,...,...,...,...,...,...,...,...,...,...,...
41210,539760,15036,Assorted Colours Silk Fan,12,2010-12-21 17:16:00,0.75,17400,United Kingdom,Completed,2010-12-21,2010-12-20
19055,537827,22145,Christmas Craft Heart Stocking,30,2010-12-08 14:43:00,2.10,15332,Lithuania,Completed,2010-12-08,2010-12-06
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,0,United Kingdom,Completed,2010-12-03,2010-11-29
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,0,United Kingdom,Completed,2010-12-09,2010-12-06
42301,539981,85099B,Jumbo Bag Red Retrospot,10,2010-12-23 14:35:00,1.95,13304,United Kingdom,Completed,2010-12-23,2010-12-20

In [166]:
df['Country'].unique()

array(['United Kingdom', 'Germany', 'Switzerland', 'Ireland', 'Finland',
       'France', 'Spain', 'Belgium', 'Japan', 'Poland', 'Cyprus',
       'Norway', 'Iceland', 'Portugal', 'Australia', 'Lithuania',
       'Netherlands', 'Italy', 'Austria', 'Sweden', 'Denmark',
       'Channel Islands'], dtype=object)

In [167]:
df['Country'] = df['Country'].str.replace('EIRE', 'Ireland')

In [168]:
df[df['Country']=='EIRE']

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Order_Status, Invoice_Date_Only, Week_Beginning]
Index: []

In [169]:
df[(df['Quantity'] < 0) & (df['Order_Status']=='Completed') & (df['Price']==0) & (df['Customer ID']==0)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
14217,537466,21488,Unknown,-50,2010-12-07 10:33:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
14064,537453,21248,Unknown,-18,2010-12-07 09:28:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
7205,537013,35965,Unknown,-25,2010-12-03 15:40:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
4347,536764,84952C,Unknown,-38,2010-12-02 14:42:00,0.0,0,United Kingdom,Completed,2010-12-02,2010-11-29
22581,538173,22353,Unknown,-28,2010-12-10 09:35:00,0.0,0,United Kingdom,Completed,2010-12-10,2010-12-06
7193,537001,21653,Unknown,-6,2010-12-03 15:33:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
14065,537454,21349,Unknown,-44,2010-12-07 09:30:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
20394,538043,22833,Unknown,-1,2010-12-09 13:10:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
7212,537020,21807,Unknown,-30,2010-12-03 15:43:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
7201,537010,22162,Unknown,-40,2010-12-03 15:38:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
20494,538054,85167B,Unknown,-24,2010-12-09 13:34:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
19599,537870,21486,Unknown,-77,2010-12-08 17:08:00,0.0,0,United Kingdom,Completed,2010-12-08,2010-12-06
22294,538159,21324,Unknown,-18,2010-12-09 17:17:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06

In [170]:
#Dealing with Nulls/NA
#Description, Price, Customer ID has nulls

In [171]:
#Description nulls
df[df['Description'].isna()]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Order_Status, Invoice_Date_Only, Week_Beginning]
Index: []

In [172]:
df['Description'] = df['Description'].fillna('UNKNOWN')

In [173]:
df['Description']=df['Description'].replace('UNKNOWN','Unknown')

In [174]:
df[df['Description'].isnull()]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, Order_Status, Invoice_Date_Only, Week_Beginning]
Index: []

In [175]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,0,United Kingdom,Completed,2010-12-21,2010-12-20
33310,539246,85114C,Red Enchanted Forest Placemat,8,2010-12-16 13:33:00,1.65,14606,United Kingdom,Completed,2010-12-16,2010-12-13
624,536415,22910,Paper Chain Kit Vintage Christmas,5,2010-12-01 11:57:00,2.95,12838,United Kingdom,Completed,2010-12-01,2010-11-29
11578,537254,20975,12 Pencils Small Tube Red Retrospot,4,2010-12-06 11:01:00,0.65,15898,United Kingdom,Completed,2010-12-06,2010-12-06
30427,538864,21485,Retrospot Heart Hot Water Bottle,24,2010-12-14 14:26:00,4.25,17739,United Kingdom,Completed,2010-12-14,2010-12-13
...,...,...,...,...,...,...,...,...,...,...,...
41210,539760,15036,Assorted Colours Silk Fan,12,2010-12-21 17:16:00,0.75,17400,United Kingdom,Completed,2010-12-21,2010-12-20
19055,537827,22145,Christmas Craft Heart Stocking,30,2010-12-08 14:43:00,2.10,15332,Lithuania,Completed,2010-12-08,2010-12-06
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,0,United Kingdom,Completed,2010-12-03,2010-11-29
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,0,United Kingdom,Completed,2010-12-09,2010-12-06
42301,539981,85099B,Jumbo Bag Red Retrospot,10,2010-12-23 14:35:00,1.95,13304,United Kingdom,Completed,2010-12-23,2010-12-20

In [176]:
#Price nulls 
df[df['Price']==0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
14217,537466,21488,Unknown,-50,2010-12-07 10:33:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
41476,539856,22626,Black Kitchen Scales,3,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
41449,539856,85123A,White Hanging Heart T-Light Holder,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
14384,537534,22550,Holiday Fun Ludo,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
19625,537872,21595,Unknown,1,2010-12-08 18:07:00,0.0,0,United Kingdom,Completed,2010-12-08,2010-12-06
41456,539856,37333,"Retro ""Tea For One""",1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
7191,536999,21421,Unknown,110,2010-12-03 15:32:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
41490,539856,22374,Airline Bag Vintage Jet Set Red,3,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
41462,539856,22684,French Blue Metal Door Sign 9,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
14354,537534,22501,Picnic Basket Wicker Large,2,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
1985,536547,37509,Unknown,1,2010-12-01 14:33:00,0.0,0,United Kingdom,Completed,2010-12-01,2010-11-29
41484,539856,22514,Childs Garden Spade Blue,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
14335,537534,85064,Cream Sweetheart Letter Rack,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
14064,537453,21248,Unknown,-18,2010-12-07 09:28:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
41496,539856,22360,Glass Jar English Confectionery,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
7205,537013,35965,Unknown,-25,2010-12-03 15:40:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
4347,536764,84952C,Unknown,-38,2010-12-02 14:42:00,0.0,0,United Kingdom,Completed,2010-12-02,2010-11-29
41473,539856,22665,Recipe Box Blue Sketchbook Design,2,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
14350,537534,22619,Set Of 6 Soldier Skittles,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
22581,538173,22353,Unknown,-28,2010-12-10 09:35:00,0.0,0,United Kingdom,Completed,2010-12-10,2010-12-06
41094,539750,21481,Fawn Blue Hot Water Bottle,1,2010-12-21 15:40:00,0.0,0,United Kingdom,Completed,2010-12-21,2010-12-20
14365,537534,22376,Airline Bag Vintage Jet Set White,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
40089,539722,22423,Regency Cakestand 3 Tier,10,2010-12-21 13:45:00,0.0,14911,Ireland,Completed,2010-12-21,2010-12-20
7193,537001,21653,Unknown,-6,2010-12-03 15:33:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
20330,538038,21488,Unknown,8,2010-12-09 13:07:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
41503,539856,22550,Holiday Fun Ludo,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
41466,539856,22681,French Blue Metal Door Sign 6,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
14065,537454,21349,Unknown,-44,2010-12-07 09:30:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
41502,539856,21791,Vintage Heads And Tails Card Game,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
19628,537877,21661,Unknown,1,2010-12-08 18:08:00,0.0,0,United Kingdom,Completed,2010-12-08,2010-12-06
12068,537361,21777,Unknown,5,2010-12-06 12:34:00,0.0,0,United Kingdom,Completed,2010-12-06,2010-12-06
14366,537534,22375,Airline Bag Vintage Jet Set Brown,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
30603,538877,21479,White Skull Hot Water Bottle,1,2010-12-14 15:29:00,0.0,0,United Kingdom,Completed,2010-12-14,2010-12-13
20394,538043,22833,Unknown,-1,2010-12-09 13:10:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
34608,539413,22959,Unknown,12,2010-12-17 13:44:00,0.0,0,United Kingdom,Completed,2010-12-17,2010-12-13
1510,536545,21134,Unknown,1,2010-12-01 14:32:00,0.0,0,United Kingdom,Completed,2010-12-01,2010-11-29
41471,539856,22676,French Blue Metal Door Sign 1,5,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
14348,537534,22625,Red Kitchen Scales,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
14353,537534,22502,Picnic Basket Wicker Small,29,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
7212,537020,21807,Unknown,-30,2010-12-03 15:43:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
7201,537010,22162,Unknown,-40,2010-12-03 15:38:00,0.0,0,United Kingdom,Completed,2010-12-03,2010-11-29
21789,538139,84802A,Unknown,2,2010-12-09 15:57:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
20494,538054,85167B,Unknown,-24,2010-12-09 13:34:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
22295,538160,20956,Unknown,288,2010-12-09 17:18:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
41457,539856,22843,Biscuit Tin Vintage Green,1,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
41488,539856,22428,Enamel Fire Bucket Cream,4,2010-12-22 14:41:00,0.0,0,United Kingdom,Completed,2010-12-22,2010-12-20
19599,537870,21486,Unknown,-77,2010-12-08 17:08:00,0.0,0,United Kingdom,Completed,2010-12-08,2010-12-06
21791,538143,84534B,Unknown,1,2010-12-09 15:58:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06
41072,539750,21080,Set/20 Red Retrospot Paper Napkins,2,2010-12-21 15:40:00,0.0,0,United Kingdom,Completed,2010-12-21,2010-12-20
2022,536552,20950,Unknown,1,2010-12-01 14:34:00,0.0,0,United Kingdom,Completed,2010-12-01,2010-11-29
14356,537534,22473,Tv Dinner Tray Vintage Paisley,1,2010-12-07 11:48:00,0.0,0,United Kingdom,Completed,2010-12-07,2010-12-06
22294,538159,21324,Unknown,-18,2010-12-09 17:17:00,0.0,0,United Kingdom,Completed,2010-12-09,2010-12-06

In [177]:
#Customer ID nulls
df[df['Customer ID']==0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,0,United Kingdom,Completed,2010-12-21,2010-12-20
11359,537240,85177,Basket Of Flowers Sewing Kit,2,2010-12-06 10:08:00,1.66,0,United Kingdom,Completed,2010-12-06,2010-12-06
21278,538071,85096,Hilda Candy Spot Rabbit,1,2010-12-09 14:09:00,7.62,0,United Kingdom,Completed,2010-12-09,2010-12-06
40813,539743,22135,Mini Ladle Love Heart Pink,1,2010-12-21 15:20:00,0.85,0,United Kingdom,Completed,2010-12-21,2010-12-20
10709,537237,82582,Area Patrolled Metal Sign,1,2010-12-06 09:58:00,4.21,0,United Kingdom,Completed,2010-12-06,2010-12-06
...,...,...,...,...,...,...,...,...,...,...,...
5859,536876,22419,Lipstick Pen Red,7,2010-12-03 11:36:00,0.85,0,United Kingdom,Completed,2010-12-03,2010-11-29
10331,537237,21641,Assorted Tutti Frutti Keyring Ball,1,2010-12-06 09:58:00,1.66,0,United Kingdom,Completed,2010-12-06,2010-12-06
22610,538177,20682,Red Retrospot Childrens Umbrella,2,2010-12-10 09:51:00,6.77,0,United Kingdom,Completed,2010-12-10,2010-12-06
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,0,United Kingdom,Completed,2010-12-03,2010-11-29
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,0,United Kingdom,Completed,2010-12-09,2010-12-06

In [178]:
df['Customer ID']=df['Customer ID'].fillna(0)

In [179]:
df[df['Customer ID']==0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,0,United Kingdom,Completed,2010-12-21,2010-12-20
11359,537240,85177,Basket Of Flowers Sewing Kit,2,2010-12-06 10:08:00,1.66,0,United Kingdom,Completed,2010-12-06,2010-12-06
21278,538071,85096,Hilda Candy Spot Rabbit,1,2010-12-09 14:09:00,7.62,0,United Kingdom,Completed,2010-12-09,2010-12-06
40813,539743,22135,Mini Ladle Love Heart Pink,1,2010-12-21 15:20:00,0.85,0,United Kingdom,Completed,2010-12-21,2010-12-20
10709,537237,82582,Area Patrolled Metal Sign,1,2010-12-06 09:58:00,4.21,0,United Kingdom,Completed,2010-12-06,2010-12-06
...,...,...,...,...,...,...,...,...,...,...,...
5859,536876,22419,Lipstick Pen Red,7,2010-12-03 11:36:00,0.85,0,United Kingdom,Completed,2010-12-03,2010-11-29
10331,537237,21641,Assorted Tutti Frutti Keyring Ball,1,2010-12-06 09:58:00,1.66,0,United Kingdom,Completed,2010-12-06,2010-12-06
22610,538177,20682,Red Retrospot Childrens Umbrella,2,2010-12-10 09:51:00,6.77,0,United Kingdom,Completed,2010-12-10,2010-12-06
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,0,United Kingdom,Completed,2010-12-03,2010-11-29
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,0,United Kingdom,Completed,2010-12-09,2010-12-06

In [180]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9974 entries, 39870 to 42301
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Invoice            9974 non-null   object
 1   StockCode          9974 non-null   object
 2   Description        9974 non-null   object
 3   Quantity           9974 non-null   int64
 4   InvoiceDate        9974 non-null   datetime64[ns]
 5   Price              9974 non-null   float64
 6   Customer ID        9974 non-null   Int64
 7   Country            9974 non-null   object
 8   Order_Status       9974 non-null   object
 9   Invoice_Date_Only  9974 non-null   object
 10  Week_Beginning     9974 non-null   datetime64[ns]
dtypes: Int64(1), datetime64[ns](2), float64(1), int64(1), object(6)
memory usage: 944.8+ KB

In [181]:
#Set Data Types

In [182]:
df.dtypes

Invoice                      object
StockCode                    object
Description                  object
Quantity                      int64
InvoiceDate          datetime64[ns]
Price                       float64
Customer ID                   Int64
Country                      object
Order_Status                 object
Invoice_Date_Only            object
Week_Beginning       datetime64[ns]
dtype: object

In [183]:
df['Invoice'] = pd.to_numeric(df['Invoice'], errors='coerce')

In [184]:
print(df['Invoice'].dtype)

int64

In [185]:
df['Invoice_Date_Only'] = pd.to_datetime(df['Invoice_Date_Only'])

In [186]:
print(df['Invoice_Date_Only'].dtype)

datetime64[ns]

In [187]:
df.dtypes

Invoice                       int64
StockCode                    object
Description                  object
Quantity                      int64
InvoiceDate          datetime64[ns]
Price                       float64
Customer ID                   Int64
Country                      object
Order_Status                 object
Invoice_Date_Only    datetime64[ns]
Week_Beginning       datetime64[ns]
dtype: object

In [188]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Order_Status,Invoice_Date_Only,Week_Beginning
39870,539708,35924,Hanging Fairy Cake Decoration,1,2010-12-21 12:18:00,4.21,0,United Kingdom,Completed,2010-12-21,2010-12-20
33310,539246,85114C,Red Enchanted Forest Placemat,8,2010-12-16 13:33:00,1.65,14606,United Kingdom,Completed,2010-12-16,2010-12-13
624,536415,22910,Paper Chain Kit Vintage Christmas,5,2010-12-01 11:57:00,2.95,12838,United Kingdom,Completed,2010-12-01,2010-11-29
11578,537254,20975,12 Pencils Small Tube Red Retrospot,4,2010-12-06 11:01:00,0.65,15898,United Kingdom,Completed,2010-12-06,2010-12-06
30427,538864,21485,Retrospot Heart Hot Water Bottle,24,2010-12-14 14:26:00,4.25,17739,United Kingdom,Completed,2010-12-14,2010-12-13
...,...,...,...,...,...,...,...,...,...,...,...
41210,539760,15036,Assorted Colours Silk Fan,12,2010-12-21 17:16:00,0.75,17400,United Kingdom,Completed,2010-12-21,2010-12-20
19055,537827,22145,Christmas Craft Heart Stocking,30,2010-12-08 14:43:00,2.10,15332,Lithuania,Completed,2010-12-08,2010-12-06
5513,536864,21488,Red White Scarf Hot Water Bottle,1,2010-12-03 11:27:00,8.47,0,United Kingdom,Completed,2010-12-03,2010-11-29
22171,538153,82599,Fanny'S Rest Stopmetal Sign,1,2010-12-09 16:31:00,4.21,0,United Kingdom,Completed,2010-12-09,2010-12-06
42301,539981,85099B,Jumbo Bag Red Retrospot,10,2010-12-23 14:35:00,1.95,13304,United Kingdom,Completed,2010-12-23,2010-12-20